-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Usuario"
(
    "idUsuario" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome character varying(150) NOT NULL,
    email character varying(150) NOT NULL,
    "senhaHash" text NOT NULL,
    PRIMARY KEY ("idUsuario"),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Coordenador"
(
    "idUsuario" integer NOT NULL,
    status boolean NOT NULL,
    PRIMARY KEY ("idUsuario")
);

CREATE TABLE IF NOT EXISTS public."Aluno"
(
    "idUsuario" integer NOT NULL,
    "totalHoras" numeric(5, 2) NOT NULL,
    matricula character varying(30) NOT NULL,
    PRIMARY KEY ("idUsuario"),
    UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS public."Curso"
(
    "idCurso" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome character varying(150) NOT NULL,
    "cargaHorariaMinima" integer NOT NULL,
    status boolean NOT NULL,
    descricao text,
    codigo character varying(30),
    PRIMARY KEY ("idCurso"),
    UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public."Matricula"
(
    "Curso_idCurso" integer NOT NULL,
    "Aluno_idUsuario" integer NOT NULL,
    "dataMatricula" date NOT NULL,
    "idStatusMatricula" integer NOT NULL,
    CONSTRAINT pk_curso_aluno PRIMARY KEY ("Curso_idCurso", "Aluno_idUsuario")
);

CREATE TABLE IF NOT EXISTS public."CoordenacaoCurso"
(
    "Curso_idCurso" integer NOT NULL,
    "Coordenador_idUsuario" integer NOT NULL,
    "dataInicio" date NOT NULL,
    "dataFim" date,
    PRIMARY KEY ("Curso_idCurso", "Coordenador_idUsuario")
);

CREATE TABLE IF NOT EXISTS public."StatusMatricula"
(
    "idStatusMatricula" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome character varying(30) NOT NULL,
    PRIMARY KEY ("idStatusMatricula")
);

CREATE TABLE IF NOT EXISTS public."SuperAdmin"
(
    "idUsuario" integer NOT NULL,
    PRIMARY KEY ("idUsuario")
);

CREATE TABLE IF NOT EXISTS public."Turno"
(
    "idTurno" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    turno character varying(30) NOT NULL,
    PRIMARY KEY ("idTurno")
);

CREATE TABLE IF NOT EXISTS public."Turno_Curso"
(
    "Turno_idTurno" integer NOT NULL,
    "Curso_idCurso" integer NOT NULL,
    CONSTRAINT fk_turno_curso PRIMARY KEY ("Turno_idTurno", "Curso_idCurso")
);

CREATE TABLE IF NOT EXISTS public."TipoAtividade"
(
    "idTipoAtividade" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome character varying(30) NOT NULL,
    PRIMARY KEY ("idTipoAtividade")
);

CREATE TABLE IF NOT EXISTS public."AtividadeComplementar"
(
    "idAtividadeComplementar" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    descricao text,
    "cargaHorariaSolicitada" integer NOT NULL,
    "tipoAtividade" integer NOT NULL,
    PRIMARY KEY ("idAtividadeComplementar")
);

CREATE TABLE IF NOT EXISTS public."RegraAtividade"
(
    "TipoAtividade_idTipoAtividade" integer NOT NULL,
    "Curso_idCurso" integer NOT NULL,
    "limiteHoras" integer NOT NULL,
    "exigeComprovante" boolean NOT NULL,
    CONSTRAINT "fk_TipoAtividade_Curso" PRIMARY KEY ("TipoAtividade_idTipoAtividade", "Curso_idCurso")
);

CREATE TABLE IF NOT EXISTS public."Telefone"
(
    "idTelefone" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    numero character varying(20) NOT NULL,
    "idUsuario" integer NOT NULL,
    PRIMARY KEY ("idTelefone"),
    UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS public."Submissao"
(
    "idSubmissao" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "dataEnvio" date NOT NULL,
    "observacaoCoordenador" text,
    "idAluno" integer NOT NULL,
    "atividadeComplementa" integer NOT NULL,
    "statusSubmissao" integer NOT NULL,
    certificado integer NOT NULL,
    "idCoordenador" integer,
    PRIMARY KEY ("idSubmissao"),
    CONSTRAINT "atividadeComplementar" UNIQUE ("atividadeComplementa"),
    CONSTRAINT certificado UNIQUE (certificado)
);

CREATE TABLE IF NOT EXISTS public."StatusSubmissao"
(
    "idStatusSubmissao" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "nomeStatus" character varying(30) NOT NULL,
    PRIMARY KEY ("idStatusSubmissao")
);

CREATE TABLE IF NOT EXISTS public."NotificacaoEmail"
(
    "idNotificacaoEmail" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    assunto character varying(250) NOT NULL,
    corpo text NOT NULL,
    data date NOT NULL,
    "idSubmissao" integer NOT NULL,
    PRIMARY KEY ("idNotificacaoEmail")
);

CREATE TABLE IF NOT EXISTS public."Certificado"
(
    "idCertificado" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "nomeArquivo" character varying(150) NOT NULL,
    "urlArquivo" character varying(250),
    "textoExtraidoOcr" character varying(250),
    "cargaHorariaOcr" character varying(250),
    "dataCertificadoOcr" character varying(250),
    "cursoOcr" character varying(250),
    "instituicaoOcr" character varying(250),
    "dataUpload" date NOT NULL,
    PRIMARY KEY ("idCertificado"),
    CONSTRAINT nome UNIQUE ("nomeArquivo"),
    CONSTRAINT url UNIQUE ("urlArquivo")
);

CREATE TABLE IF NOT EXISTS public."LogAuditoria"
(
    "idLogauditoria" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "dataHora" date NOT NULL,
    "idEntidadeAfetada" integer NOT NULL,
    descricao character varying(200),
    "ipOrigem" character varying(45) NOT NULL,
    "idUsuario" integer NOT NULL,
    "idTipoAcao" integer NOT NULL,
    PRIMARY KEY ("idLogauditoria")
);

CREATE TABLE IF NOT EXISTS public."TipoAcao"
(
    "idTipoAcao" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    acao character varying(150) NOT NULL,
    PRIMARY KEY ("idTipoAcao")
);

ALTER TABLE IF EXISTS public."Coordenador"
    ADD CONSTRAINT fk_coordenador_usuario FOREIGN KEY ("idUsuario")
    REFERENCES public."Usuario" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Aluno"
    ADD CONSTRAINT fk_aluno_usuario FOREIGN KEY ("idUsuario")
    REFERENCES public."Usuario" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT fk_curso FOREIGN KEY ("Curso_idCurso")
    REFERENCES public."Curso" ("idCurso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT fk_aluno FOREIGN KEY ("Aluno_idUsuario")
    REFERENCES public."Aluno" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Matricula"
    ADD FOREIGN KEY ("idStatusMatricula")
    REFERENCES public."StatusMatricula" ("idStatusMatricula") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public."CoordenacaoCurso"
    ADD CONSTRAINT fk_curso FOREIGN KEY ("Curso_idCurso")
    REFERENCES public."Curso" ("idCurso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."CoordenacaoCurso"
    ADD CONSTRAINT "fk_Coordenador" FOREIGN KEY ("Coordenador_idUsuario")
    REFERENCES public."Coordenador" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."SuperAdmin"
    ADD FOREIGN KEY ("idUsuario")
    REFERENCES public."Usuario" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Turno_Curso"
    ADD CONSTRAINT fk_turno FOREIGN KEY ("Turno_idTurno")
    REFERENCES public."Turno" ("idTurno") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Turno_Curso"
    ADD CONSTRAINT fk_curso FOREIGN KEY ("Curso_idCurso")
    REFERENCES public."Curso" ("idCurso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."AtividadeComplementar"
    ADD CONSTRAINT "fk_tipoAtividade" FOREIGN KEY ("tipoAtividade")
    REFERENCES public."TipoAtividade" ("idTipoAtividade") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public."RegraAtividade"
    ADD CONSTRAINT "fk_TipoAtividade" FOREIGN KEY ("TipoAtividade_idTipoAtividade")
    REFERENCES public."TipoAtividade" ("idTipoAtividade") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."RegraAtividade"
    ADD CONSTRAINT "fk_Curso" FOREIGN KEY ("Curso_idCurso")
    REFERENCES public."Curso" ("idCurso") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Telefone"
    ADD CONSTRAINT fk_coordenador FOREIGN KEY ("idUsuario")
    REFERENCES public."Coordenador" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Submissao"
    ADD CONSTRAINT fk_aluno FOREIGN KEY ("idAluno")
    REFERENCES public."Aluno" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Submissao"
    ADD CONSTRAINT "fk_atividadeComplementar" FOREIGN KEY ("atividadeComplementa")
    REFERENCES public."AtividadeComplementar" ("idAtividadeComplementar") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Submissao"
    ADD CONSTRAINT fk_status FOREIGN KEY ("statusSubmissao")
    REFERENCES public."StatusSubmissao" ("idStatusSubmissao") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public."Submissao"
    ADD CONSTRAINT fk_certificado FOREIGN KEY (certificado)
    REFERENCES public."Certificado" ("idCertificado") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public."Submissao"
    ADD CONSTRAINT fk_coordenador FOREIGN KEY ("idCoordenador")
    REFERENCES public."Coordenador" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public."NotificacaoEmail"
    ADD CONSTRAINT fk_submissao FOREIGN KEY ("idSubmissao")
    REFERENCES public."Submissao" ("idSubmissao") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."LogAuditoria"
    ADD CONSTRAINT "fk_Usuario" FOREIGN KEY ("idUsuario")
    REFERENCES public."Usuario" ("idUsuario") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public."LogAuditoria"
    ADD CONSTRAINT "fk_tipoAcao" FOREIGN KEY ("idTipoAcao")
    REFERENCES public."TipoAcao" ("idTipoAcao") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
-- Inserir status padrão
/*INSERT INTO public."StatusSubmissao" ("idStatusSubmissao", "nomeStatus")
VALUES 
( 'PENDENTE'),
( 'APROVADA'),
( 'REPROVADA')
ON CONFLICT DO NOTHING;*/
INSERT INTO public."StatusSubmissao" ("nomeStatus")
VALUES 
('PENDENTE'),
('APROVADA'),
('REPROVADA')
ON CONFLICT DO NOTHING;

-- Definir PENDENTE como padrão
ALTER TABLE public."Submissao"
ALTER COLUMN "statusSubmissao" SET DEFAULT 1;


END;